#eureka:
#    client:
#        service-url:
#            defaultZone: http://localhost:8888/eureka/
#logging:
#    level:
#        org:
#            springframework:
#                security: DEBUG
#server:
#    port: 8081
#spring:
#    application:
#        name: authentication_service
#    datasource:
#        driverClassName: org.h2.Driver
#        password: password
#        platform: h2
#        url: jdbc:h2:mem:testdb
#        username: sa
#    h2:
#        console:
#            enabled: true
#            path: /h2-console
#
#
#
#
#
